name: quadpkgs
description: QuadOS Packages
version: 1.0.0
repository: https://github.com/Quad-Linux/quadpkgs
publish_to: none

environment:
  sdk: ^3.4.4

dependencies:
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  lints: ^4.0.0
